repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: end-of-file-fixer
        exclude: requirements.txt
      - id: check-yaml
      - id: check-json
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: double-quote-string-fixer

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        exclude: base_models.py
        args: [--profile, black, --filter-files]

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.4.0
    hooks:
      - id: add-trailing-comma

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args: [--py310-plus]

  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.1
    hooks:
      - id: autopep8

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        exclude: base_models.py
        args: ["--ignore=E501"]
