version: '3.8'

services:

  db:
    image: postgres:15.1-alpine
    restart: always
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ../.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: ../
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ../.env
    ports:
      - "8000:8000"
    volumes:
      - ../:/app
    depends_on:
      db:
        condition: service_healthy