version: '3.8'

services:

  db:
    container_name: test_restaurant_db
    image: postgres:15.1-alpine
    restart: always
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ../.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  test_web:
    container_name: test_restaurant_web
    build:
      context: ../
      dockerfile: Dockerfile
    env_file:
      - ../.env
    command: "python -m pytest -vv"
    volumes:
      - ../:/app
    depends_on:
      db:
        condition: service_healthy