version: '3.8'

services:

  db:
    container_name: test_restaurant_db
    image: postgres:15.1-alpine
    restart: always
    user: postgres
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ../.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: restaurant_redis
    restart: always
    volumes:
      - ./redis/data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    expose:
      - 6379
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 20s
      retries: 100

  test_web:
    container_name: test_restaurant_web
    build:
      context: ../
      dockerfile: Dockerfile
    env_file:
      - ../.env
    command: bash -c "alembic upgrade head && python -m pytest -vv"
    volumes:
      - ../:/app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
