version: '3.8'

services:

  db:
    image: postgres:15.1-alpine
    restart: always
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ../.env
  web:
    build: ../
    restart: always
    env_file:
      - ../.env
    ports:
      - "8000:8000"
    depends_on:
      - db