"""init

Revision ID: 9876e70b2ac8
Revises:
Create Date: 2023-02-01 00:46:01.293150

"""
import sqlalchemy as sa

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "9876e70b2ac8"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "menus",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_menus_id"), "menus", ["id"], unique=False)
    op.create_table(
        "submenus",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("menu_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["menu_id"], ["menus.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_submenus_id"), "submenus", ["id"], unique=False)
    op.create_index(op.f("ix_submenus_menu_id"), "submenus", ["menu_id"], unique=False)
    op.create_table(
        "dishes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("submenu_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["submenu_id"], ["submenus.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_dishes_id"), "dishes", ["id"], unique=False)
    op.create_index(
        op.f("ix_dishes_submenu_id"), "dishes", ["submenu_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_dishes_submenu_id"), table_name="dishes")
    op.drop_index(op.f("ix_dishes_id"), table_name="dishes")
    op.drop_table("dishes")
    op.drop_index(op.f("ix_submenus_menu_id"), table_name="submenus")
    op.drop_index(op.f("ix_submenus_id"), table_name="submenus")
    op.drop_table("submenus")
    op.drop_index(op.f("ix_menus_id"), table_name="menus")
    op.drop_table("menus")
    # ### end Alembic commands ###
